services:
  # Backend API
  - type: web
    name: stock-management-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: APP_NAME
        value: Stock Management
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:VzUcQMilq2IZUPmtCLx2gySvVu4H11QHZAT+joKp1JM=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://stock-management-backend.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: stock-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: stock-management-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: stock-management-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: stock-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stock-management-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: public
      - key: SANCTUM_STATEFUL_DOMAINS
        value: stock-management-front-wvmn.onrender.com
      - key: SESSION_DOMAIN
        value: .onrender.com
      - key: FRONTEND_URL
        value: https://stock-management-front-wvmn.onrender.com

databases:
  - name: stock-management-db
    plan: free
    databaseName: stock_management
    user: stock_user
